name: CI/CD and create image docker

# Disparadores do workflow
on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

# Job 1: Build e Deploy para Vercel
jobs:
  build-and-deploy-vercel:
    runs-on: ubuntu-latest  # Usa a última versão do Ubuntu como máquina virtual
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'  # Defina a versão do Node.js (alterável conforme o projeto)

      - name: Install dependencies
        run: npm install

      #- name: Run tests
       # run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build project
        run: npm run build --prod

      - name: Deploy to Vercel
        run: vercel --prod  # Use a CLI do Vercel para fazer o deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
          
# Job 2 Criar e Enviar a imagem Docker para o Docker Hub
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-deploy-vercel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build end push Docker image
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: asfuture/currencyconverter:latest
